### ISSUE TITLE
Publish to Github Pages

### ISSUE THREAD

**Issue by whilestevego** [jonfur/bootstrap-profile#3]
Github pages is a service offered by Github to publish your static website (meaning that your website runs a server backend) directly from a special branch named `gh-pages` on your repo. I want you to publish your project with that service! :shipit:

[Here's a guide on Github Pages!](https://www.thinkful.com/learn/a-guide-to-using-github-pages/start/existing-project/project-page/existing-repo/) Let me know if you have any questions.

**Comment by whilestevego** [comment]
Since you finished this issue, you should close and comment that it's done. :sunglasses:

**Comment by jonfur** [comment]
Aha! All done! :smiley:
